---
title: "Fisheries Datasets by Topic"
output: rmarkdown::html_vignette
---

The following list is a comprehensive(?) list of fisheries related datasets found in packages that exist on CRAN. Datasets from packages other than FSA and FSAdata are entered manually so please submit a GitHub [Issue](https://github.com/fishR-Core-Team/FSAdata/issues) or [Pull Request](https://github.com/fishR-Core-Team/FSAdata/pulls) with any corrections or additions. This list was last updated on `r format(Sys.Date(),format="%B %d, %Y")`.

&nbsp;

```{r setup, include=FALSE}
source("zHelpers.R")
```

```{r results='asis'}
## Get dataset list from other packages
## Datasets from other packages are manually entered into
##   DataFromOtherPackages.xlsx. Make sure to "Clean and Install" the package
##   locally so that updates will be found when knitting this vignette.
tmp <- readxl::read_excel(system.file("extdata/DataFromOtherPackages.xlsx",
                                      package="FSAdata")) %>%
  select(-starts_with("Entered"))
## Database of datasets in FSA and FSAdata, with other packages appended
fish_db <- rbind(prepare_db("FSA"),prepare_db("FSAdata"),tmp)

maketable(fish_db,topics)
```
